#网络类型
type: mysql
#数据库 服务器地址
url: "tcp(127.0.0.1:3306)/full_frame?charset=utf8"
#用户名
username: "root"
#密码
password: "19880727"
#最大空闲链接数  默认8
max_idle: 8
#表示和数据库的最大链接数， 默认0表示没有限制
max_active: 16
#最大空闲时间  默认100ms 毫秒
idle_timeout: 100

