#网络类型
type: mysql
#数据库名
dbname: "full_frame"
#连接参数
params: "charset=utf8"
#数据库服务器地址
hostname: "127.0.0.1:3306"
#网络类型
network: "tcp"
#用户名
username: "root"
#密码
password: "19880727"
#最大空闲链接数  默认8
max_idle: 8
#表示和数据库的最大链接数， 默认0表示没有限制
max_active: 16
#最大空闲时间  默认100ms 毫秒
idle_timeout: 100
#设置数据库闲链接超时时间 默认 20000ms
conn_max_lifetime: 20000

