#服务配置
server:
  #是否注册服务
  register: true

  #本地服务
  local: true

  #http服务
  http:
    #监听地址
    address: ":10101"
    #crt证书
    crt: ""
    #crt密钥
    key: ""
    #基础路基
    path: ""

  #http服务
  web_socket:
    #监听地址
    address: ":10102"
    #crt证书
    crt: ""
    #crt密钥
    key: ""
    #基础路基
    path: ""

  #开启的服务
  list:
    - "admin"

#客服配置
client:
  find: true
  server:
    admin1:
      #服务名
      name: ""
      #本地服务
      local: true
      #      #http服务
      #      http: "http//127.0.0.1:10101/server"
      #      #tcp服务
      #      tcp:
      #        #监听地址
      #        address: "127.0.0.1:10100"
      #        #crt证书
      #        crt: ""
      #        #crt密钥
      #        key: ""
      #      #WebSocket服务
      #      web_socket:  "http//127.0.0.1:10102/server-ws"
    user1:
      #服务名
      name: "user1"
      #本地服务
      local: true
  #服务列表
  list:
    admin:
      - "admin1"
    user:
      - "user1"
