#机房ID
data_center_id: 1
#机器ID
worker_id: 1

#Reids配置
redis:
  #网络类型
  network: tcp
  #Redis 服务器地址
  address: "localhost:6379"
  #密码
  #password: "123456"
  #最大空闲链接数  默认8
  max_idle: 8
  #表示和数据库的最大链接数， 默认0表示没有限制
  max_active: 16
  #最大空闲时间  默认100ms 毫秒
  idle_timeout: 100

#数据库配置
db:
  #网络类型
  type: mysql
  #数据库 服务器地址
  url: "tcp(127.0.0.1:3306)/full_frame?charset=utf8"
  #用户名
  username: "root"
  #密码
  password: "19880727"
  #最大空闲链接数  默认8
  max_idle: 8
  #表示和数据库的最大链接数， 默认0表示没有限制
  max_active: 16
  #最大空闲时间  默认100ms 毫秒
  idle_timeout: 100

#
service:
  #服务配置
  server:
    #本地服务
    local: true

    #http服务
    http:
      #监听地址
      address: ":10101"
      #crt证书
      crt: ""
      #crt密钥
      key: ""
      #基础路基
      path: ""

    #http服务
    web_socket:
      #监听地址
      address: ":10102"
      #crt证书
      crt: ""
      #crt密钥
      key: ""
      #基础路基
      path: ""

    #tcp服务
    tcp:
      #监听地址
      address: ":10100"
      #crt证书
      crt: ""
      #crt密钥
      key: ""

  #客服配置
  client:
    server:
      admin1:
        #服务名
        name: ""
        #本地服务
        local: true
        #      #http服务
        #      http: "http//127.0.0.1:10101/server"
        #      #tcp服务
        #      tcp:
        #        #监听地址
        #        address: "127.0.0.1:10100"
        #        #crt证书
        #        crt: ""
        #        #crt密钥
        #        key: ""
        #      #WebSocket服务
        #      web_socket:  "http//127.0.0.1:10102/server-ws"
      user1:
        #服务名
        name: "user1"
        #本地服务
        local: true
    #服务列表
    list:
      admin:
        - "admin1"
      user:
        - "user1"
