// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto_test.proto

package hbuf_test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoBuffSub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V1            int64                  `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoBuffSub) Reset() {
	*x = ProtoBuffSub{}
	mi := &file_proto_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoBuffSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBuffSub) ProtoMessage() {}

func (x *ProtoBuffSub) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBuffSub.ProtoReflect.Descriptor instead.
func (*ProtoBuffSub) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoBuffSub) GetV1() int64 {
	if x != nil {
		return x.V1
	}
	return 0
}

type ProtoBuffTest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// int32 v1 = 1;
	// uint32 v2 = 2;
	V2 *int64 `protobuf:"varint,2,opt,name=v2,proto3,oneof" json:"v2,omitempty"`
	V3 int64  `protobuf:"varint,3,opt,name=v3,proto3" json:"v3,omitempty"`
	// uint64 v4 = 4;
	// sint32 v5 = 5;
	// sint64 v6 = 6;
	V7            []int64                  `protobuf:"varint,7,rep,packed,name=v7,proto3" json:"v7,omitempty"`
	V8            map[int64]int64          `protobuf:"bytes,8,rep,name=v8,proto3" json:"v8,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	V9            *ProtoBuffSub            `protobuf:"bytes,9,opt,name=v9,proto3" json:"v9,omitempty"`
	V10           []*ProtoBuffSub          `protobuf:"bytes,10,rep,name=v10,proto3" json:"v10,omitempty"`
	V11           string                   `protobuf:"bytes,11,opt,name=v11,proto3" json:"v11,omitempty"`
	V12           map[string]*ProtoBuffSub `protobuf:"bytes,12,rep,name=v12,proto3" json:"v12,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	V13           []byte                   `protobuf:"bytes,13,opt,name=v13,proto3" json:"v13,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoBuffTest) Reset() {
	*x = ProtoBuffTest{}
	mi := &file_proto_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoBuffTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBuffTest) ProtoMessage() {}

func (x *ProtoBuffTest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBuffTest.ProtoReflect.Descriptor instead.
func (*ProtoBuffTest) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoBuffTest) GetV2() int64 {
	if x != nil && x.V2 != nil {
		return *x.V2
	}
	return 0
}

func (x *ProtoBuffTest) GetV3() int64 {
	if x != nil {
		return x.V3
	}
	return 0
}

func (x *ProtoBuffTest) GetV7() []int64 {
	if x != nil {
		return x.V7
	}
	return nil
}

func (x *ProtoBuffTest) GetV8() map[int64]int64 {
	if x != nil {
		return x.V8
	}
	return nil
}

func (x *ProtoBuffTest) GetV9() *ProtoBuffSub {
	if x != nil {
		return x.V9
	}
	return nil
}

func (x *ProtoBuffTest) GetV10() []*ProtoBuffSub {
	if x != nil {
		return x.V10
	}
	return nil
}

func (x *ProtoBuffTest) GetV11() string {
	if x != nil {
		return x.V11
	}
	return ""
}

func (x *ProtoBuffTest) GetV12() map[string]*ProtoBuffSub {
	if x != nil {
		return x.V12
	}
	return nil
}

func (x *ProtoBuffTest) GetV13() []byte {
	if x != nil {
		return x.V13
	}
	return nil
}

var File_proto_test_proto protoreflect.FileDescriptor

const file_proto_test_proto_rawDesc = "" +
	"\n" +
	"\x10proto_test.proto\x12\thbuf.test\"\x1e\n" +
	"\fProtoBuffSub\x12\x0e\n" +
	"\x02v1\x18\x01 \x01(\x03R\x02v1\"\xb2\x03\n" +
	"\rProtoBuffTest\x12\x13\n" +
	"\x02v2\x18\x02 \x01(\x03H\x00R\x02v2\x88\x01\x01\x12\x0e\n" +
	"\x02v3\x18\x03 \x01(\x03R\x02v3\x12\x0e\n" +
	"\x02v7\x18\a \x03(\x03R\x02v7\x120\n" +
	"\x02v8\x18\b \x03(\v2 .hbuf.test.ProtoBuffTest.V8EntryR\x02v8\x12'\n" +
	"\x02v9\x18\t \x01(\v2\x17.hbuf.test.ProtoBuffSubR\x02v9\x12)\n" +
	"\x03v10\x18\n" +
	" \x03(\v2\x17.hbuf.test.ProtoBuffSubR\x03v10\x12\x10\n" +
	"\x03v11\x18\v \x01(\tR\x03v11\x123\n" +
	"\x03v12\x18\f \x03(\v2!.hbuf.test.ProtoBuffTest.V12EntryR\x03v12\x12\x10\n" +
	"\x03v13\x18\r \x01(\fR\x03v13\x1a5\n" +
	"\aV8Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aO\n" +
	"\bV12Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.hbuf.test.ProtoBuffSubR\x05value:\x028\x01B\x05\n" +
	"\x03_v2B\rZ\v.;hbuf_testb\x06proto3"

var (
	file_proto_test_proto_rawDescOnce sync.Once
	file_proto_test_proto_rawDescData []byte
)

func file_proto_test_proto_rawDescGZIP() []byte {
	file_proto_test_proto_rawDescOnce.Do(func() {
		file_proto_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_test_proto_rawDesc), len(file_proto_test_proto_rawDesc)))
	})
	return file_proto_test_proto_rawDescData
}

var file_proto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_test_proto_goTypes = []any{
	(*ProtoBuffSub)(nil),  // 0: hbuf.test.ProtoBuffSub
	(*ProtoBuffTest)(nil), // 1: hbuf.test.ProtoBuffTest
	nil,                   // 2: hbuf.test.ProtoBuffTest.V8Entry
	nil,                   // 3: hbuf.test.ProtoBuffTest.V12Entry
}
var file_proto_test_proto_depIdxs = []int32{
	2, // 0: hbuf.test.ProtoBuffTest.v8:type_name -> hbuf.test.ProtoBuffTest.V8Entry
	0, // 1: hbuf.test.ProtoBuffTest.v9:type_name -> hbuf.test.ProtoBuffSub
	0, // 2: hbuf.test.ProtoBuffTest.v10:type_name -> hbuf.test.ProtoBuffSub
	3, // 3: hbuf.test.ProtoBuffTest.v12:type_name -> hbuf.test.ProtoBuffTest.V12Entry
	0, // 4: hbuf.test.ProtoBuffTest.V12Entry.value:type_name -> hbuf.test.ProtoBuffSub
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_test_proto_init() }
func file_proto_test_proto_init() {
	if File_proto_test_proto != nil {
		return
	}
	file_proto_test_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_test_proto_rawDesc), len(file_proto_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_test_proto_goTypes,
		DependencyIndexes: file_proto_test_proto_depIdxs,
		MessageInfos:      file_proto_test_proto_msgTypes,
	}.Build()
	File_proto_test_proto = out.File
	file_proto_test_proto_goTypes = nil
	file_proto_test_proto_depIdxs = nil
}
